name: test
on:
  workflow_call:
  push:
  pull_request:
jobs:
  test-jvm:
    strategy:
      matrix:
        os: [ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          lein: latest
      - name: Run project unit tests
        run: lein test